baseURL = 'http://kkkfasya.github.io/blog'
languageCode = 'id-ID'
title = 'fbadtakes'
theme = 'paper'
watch = true

[params]
  color = 'wheat'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'kkkfasya'               # twitter.com/YOUR_TWITTER_ID
  github = 'kkkfasya'                 # github.com/YOUR_GITHUB_ID
  instagram = 'kkkfasya'           # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                                # show rss icon

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = false                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon
